language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO=1.4.22
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.10
  - DJANGO=1.8.6

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7.10
    - python: "2.6"
      env: DJANGO=1.8.6
    - python: "3.3"
      env: DJANGO=1.4.22
    - python: "3.4"
      env: DJANGO=1.4.22
    - python: "3.5"
      env: DJANGO=1.4.22
    - python: "3.5"
      env: DJANGO=1.5.12
    - python: "3.5"
      env: DJANGO=1.6.11
    - python: "3.5"
      env: DJANGO=1.7.10

install:
  - pip install -U Django==$DJANGO
  - pip install django-bootstrap-breadcrumbs==0.7.2
  - pip install -Ur requirements-test.txt

before_script:
  - git clone https://github.com/prymitive/bootstrap-breadcrumbs.git
  - cd bootstrap-breadcrumbs
  - rm -fr django_bootstrap_breadcrumbs

script:
  - py.test -v --pep8
