sudo: false

language: python

cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  matrix:
    - DJANGO=2.0.7
    - DJANGO=1.8.19
    - DJANGO=1.10.8
    - DJANGO=1.11.14

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.0.7
    - python: "3.6"
      env: DJANGO=1.8.19
    - python: "3.6"
      env: DJANGO=1.10.8

install:
  - pip install -U Django==$DJANGO
  - pip install django-bootstrap-breadcrumbs==0.9.1
  - pip install -Ur requirements-test.txt

before_script:
  - git clone https://github.com/prymitive/bootstrap-breadcrumbs.git
  - cd bootstrap-breadcrumbs
  - git checkout v0.9.2
  - rm -fr django_bootstrap_breadcrumbs

script:
  - py.test -v --pep8
